# Import

In [13]:
if False:
    !sudo /bin/bash -c "(source /venv/bin/activate; pip install --quiet jupyterlab-vim)"
    !jupyter labextension enable

In [14]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [5]:
import helpers.hgoogle_drive_api as hgodrapi

hgodrapi.install_needed_modules()

/app/helpers_root/helpers/hpandas_utils.py:12: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  import tqdm.autonotebook as tauton
WARNING: No module named 'googleapiclient'

Module 'google' is already installed.
Installing module 'googleapiclient'...

Module 'gspread' is already installed.

In [6]:
import logging

import helpers.hdbg as hdbg
import helpers.henv as henv
import helpers.hprint as hprint

print(henv.get_system_signature()[0])

hnotebook.config_notebook()

# hdbg.init_logger(verbosity=logging.DEBUG)
hdbg.init_logger(verbosity=logging.INFO)
# hdbg.test_logger()
_LOG = logging.getLogger(__name__)

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (arm64v8)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

# System signature
  # Container version
    container_version='2.0.0'
    changelog_version='2.2.0'
  # Git info
    branch_name='CsfyTask7819_Add_blogs'
    hash='ec5f1fa0dd'
    # Last commits:
      * ec5f1fa0dd GP Saggese Update                                                            (  23 hours ago) Sun Jan 18 03:46:17 2026  (HEAD -> CsfyTask7819_Add_blogs, origin/CsfyTask7819_Add_blogs)
      * 0730d32274 GP Saggese Update                                                            (    6 days ago) Tue Jan 13 01:33:48 2026
      * d9e36eaa67 GP Saggese Merge                                                             (    9 days ago) Sat Jan 10 01:18:07 2026
  # Platform info
    system=Linux
    node name=ced076cfec92
    release=6.10.14-linuxkit
    version=#1 SMP Tue Apr 15 16:00:54 UTC 2025
    machine=aarch64
    processor=aarch64
  # psutils info
    cpu count=8
    cpu freq=None
    memory=svmem(total=16749285376, available=15034769408, percent=10.2, used=1451630592, free=13477457920, active=1916391424, inactive=777498624, buffers=282021888, cached=1538174976, shared=876544, slab=276332544)
    disk usage=sdiskusage(total=270233210880, used=161141297152, free=95331299328, percent=62.8)
  # Docker info
    has_docker=True
    docker_version='28.1.1'
    docker_needs_sudo=False
    has_privileged_mode=True
    is_inside_docker=True
    has_sibling_containers_support=True
    has_docker_dind_support=True
  # Packages
    python: 3.12.3
    cvxopt: 1.3.2
    cvxpy: 1.5.3
    gluonnlp: ?
    gluonts: ?
    joblib: 1.4.2
    mxnet: ?
    numpy: 2.1.3
    pandas: 2.2.3
    pyarrow: 18.0.0
    scipy: 1.14.1
    seaborn: 0.13.2
    sklearn: 1.5.2
    statsmodels: 0.14.4
WARNING: Running in Jupyter
INFO  > cmd='/venv/lib/python3.12/site-packages/ipykernel_launcher.py -f /home/.local/share/jupyter/runtime/kernel-da031886-8faf-4799-aa53-89d72533ca1f.json'

## Reload

In [7]:
import importlib
import pandas as pd

import ck_marketing.workflows as ckmktwf
import ck_marketing.plugins as ckmktpi
import helpers.hgoogle_drive_api as hgodrapi

importlib.reload(ckmktwf)
importlib.reload(ckmktpi)

# Get credentials first
credentials = hgodrapi.get_credentials(
    service_key_path="/home/.config/gspread_pandas/google_secret.json"
)

# Load data

## pitchbook.Outreach_AI_companies

In [30]:
url = "https://docs.google.com/spreadsheets/d/1GnnmtGTrHDwMP77VylEK0bSF_RLUV5BWf1iGmxuBQpI"
hgodrapi.print_info_about_google_url(url)

url: 'https://docs.google.com/spreadsheets/d/1GnnmtGTrHDwMP77VylEK0bSF_RLUV5BWf1iGmxuBQpI'
file name: 'pitchbook.Outreach_AI_companies'
tab names: '['2025-12-03', '2025-12-03-v2']'
folder path: 'Drive/Outreach pipeline/Campaigns_2025_ToReorg'

In [31]:
tab_name = "_all_"
ckmktwf.analyze_data_type(url, tab_name)

WARNING Cache hit for _get_gsheet_to_df
WARNING Cache hit for _get_gsheet_to_df
INFO  2025-12-03=(data_from_pitchbook, has_email, has_email_txt, has_merge_status)
WARNING Cache hit for _get_gsheet_to_df
WARNING Cache hit for _get_gsheet_to_df
INFO  2025-12-03-v2=(data_from_pitchbook, has_email, has_email_txt, has_merge_status)

In [32]:
tab_names = ["2025-12-03", "2025-12-03-v2"]
normalize = True
contact_df = ckmktwf.get_data_from_fuzzy_column_matching(
    url, tab_names, normalize
)

display(contact_df.head(2))
print(contact_df.shape)

WARNING Cache hit for _get_gsheet_to_df
WARNING unmatched_keys=['last_name', 'email_verification', 'personal_email', 'linkedin_url', 'company_industry', 'timestamp']
WARNING unmatched_cols=['EmailText', 'Mergestatus', 'origin_timestamp', 'email_timestamp']
WARNING Cache hit for _get_gsheet_to_df
WARNING unmatched_keys=['last_name', 'email_verification', 'personal_email', 'linkedin_url', 'company_industry', 'timestamp']
WARNING unmatched_cols=['Idx', 'EmailText', 'Batch', 'Mergestatus', 'origin_timestamp', 'email_timestamp']

                                       origin    full_name first_name                    email                                          job_title company_name    company_domain     company_type            country                                          biography
0  pitchbook.Outreach_AI_companies.2025-12-03  Aaron Levie      Aaron            aaron@box.com                  Founder & Chief Executive Officer          Box       www.box.com   Public Company   Redwood City, CA  Mr. Aaron Levie is the Founder and serves as C...
1  pitchbook.Outreach_AI_companies.2025-12-03  Ahti Heinla       Ahti  ahti.heinla@starship.co  Co-Founder, Chief Executive Officer, Chief Tec...     Starship  www.starship.xyz  Private Company  San Francisco, CA  Mr. Ahti Heinla is a Co-Founder and serves as ...

(758, 10)

In [33]:
merge_status_tabs = ["2025-12-03", "2025-12-03-v2"]
contact_df = ckmktwf.merge_yamm_results_from_gsheet(
    contact_df, url, merge_status_tabs, print_results=True
)

INFO  Found 12 / 86 = 13.95% bounced emails in df_yamm
Changed email_verification for 12 / 758 = 1.58% contacts in contact_df
INFO  Found 43 / 672 = 6.40% bounced emails in df_yamm
Changed email_verification for 43 / 758 = 5.67% contacts in contact_df

In [28]:
contact_df

                                            origin            full_name first_name                         email                                          job_title           company_name      company_domain            company_type            country                                          biography email_verification
0       pitchbook.Outreach_AI_companies.2025-12-03          Aaron Levie      Aaron                 aaron@box.com                  Founder & Chief Executive Officer                    Box         www.box.com          Public Company   Redwood City, CA  Mr. Aaron Levie is the Founder and serves as C...
1       pitchbook.Outreach_AI_companies.2025-12-03          Ahti Heinla       Ahti       ahti.heinla@starship.co  Co-Founder, Chief Executive Officer, Chief Tec...               Starship    www.starship.xyz         Private Company  San Francisco, CA  Mr. Ahti Heinla is a Co-Founder and serves as ...
2       pitchbook.Outreach_AI_companies.2025-12-03     Aidan Gomez Ph.D      Aidan               aidan@cohere.ai  Co-Founder, Board Member & Chief Executive Off...                 Cohere      www.cohere.com         Private Company    Toronto, Canada  Dr. Aidan Gomez is a Co-Founder and serves as ...
3       pitchbook.Outreach_AI_companies.2025-12-03          Aiman Ezzat      Aiman     aiman.ezzat@capgemini.com  Chief Executive Officer, Board Member & Member...              Capgemini   www.capgemini.com  Management Consultants      Paris, France  Mr. Aiman Ezzat serves as Chief Executive Offi...
4       pitchbook.Outreach_AI_companies.2025-12-03  Alexander Karp Ph.D  Alexander            akarp@palantir.com  Co-Founder, Chief Executive Officer, and Board...  Palantir Technologies    www.palantir.com          Public Company      Palo Alto, CA  Dr. Alexander Karp is a Co-Founder & serves as...
..                                             ...                  ...        ...                           ...                                                ...                    ...                 ...                     ...                ...                                                ...                ...
667  pitchbook.Outreach_AI_companies.2025-12-03-v2          Yaron Shaer      Yaron        yaron.shaer@klarna.com               Chief Technology Officer, Technology           Klarna Group      www.klarna.com          Public Company  Stockholm, Sweden  Mr. Yaron Shaer serves as Chief Technology Off...
668  pitchbook.Outreach_AI_companies.2025-12-03-v2        Yeliz Kalafat      Yeliz  yeliz.kalafat@useinsider.com                            Chief Financial Officer                Insider  www.useinsider.com         Private Company   Istanbul, Turkey  Ms. Yeliz Kalafat serves as Chief Financial Of...
669  pitchbook.Outreach_AI_companies.2025-12-03-v2               Yun Fu        Yun                  yun@otter.ai  Co-Founder, Vice President of Engineering & Ch...               Otter.ai        www.otter.ai         Private Company  Mountain View, CA  Mr. Yun Fu is a Co-Founder & serves as Chief T...
670  pitchbook.Outreach_AI_companies.2025-12-03-v2            Yuxin Ren      Yuxin          yuxinren@tencent.com  Chief Operating Officer and President of Platf...       Tencent Holdings     www.tencent.com          Public Company    Shenzhen, China  Mr. Yuxin Ren serves as Chief Operating Office...
671  pitchbook.Outreach_AI_companies.2025-12-03-v2           Zack Cable       Zack                 zack@otter.ai                              Chief Revenue Officer               Otter.ai        www.otter.ai         Private Company  Mountain View, CA  Mr. Zack Cable serves as Chief Revenue Officer...

[758 rows x 11 columns]

## Pitchbook.results

In [34]:
url = "https://docs.google.com/spreadsheets/d/1aKzWUw9mwP-2_vzz27ggeLe1sgF9OrWRWmGMo9Dk9bU"
hgodrapi.print_info_about_google_url(url)

url: 'https://docs.google.com/spreadsheets/d/1aKzWUw9mwP-2_vzz27ggeLe1sgF9OrWRWmGMo9Dk9bU'
file name: 'Pitchbook.results'
tab names: '['200AI.Corp_dev', 'Fort500.Corp_dev']'
folder path: 'Drive/Outreach pipeline/Campaigns_2025_ToReorg'

In [35]:
tab_name = "_all_"
ckmktwf.analyze_data_type(url, tab_name)

INFO  Reading data:
  url='https://docs.google.com/spreadsheets/d/1aKzWUw9mwP-2_vzz27ggeLe1sgF9OrWRWmGMo9Dk9bU'
  file_name='Pitchbook.results'
  tab_name='200AI.Corp_dev'
WARNING Cache hit for _get_gsheet_to_df
INFO  200AI.Corp_dev=(data_from_pitchbook, has_linkedin_profile, has_email)
INFO  Reading data:
  url='https://docs.google.com/spreadsheets/d/1aKzWUw9mwP-2_vzz27ggeLe1sgF9OrWRWmGMo9Dk9bU'
  file_name='Pitchbook.results'
  tab_name='Fort500.Corp_dev'
WARNING Cache hit for _get_gsheet_to_df
INFO  Fort500.Corp_dev=(data_from_pitchbook, has_linkedin_profile, has_email)

In [37]:
# tab_name = "200AI.Corp_dev"
# tab_name = "Fort500.Corp_dev"
tab_name = "_all_"
normalize = True
contact_df = ckmktwf.get_data_from_fuzzy_column_matching(
    url, tab_name, normalize
)
contact_df.head(2)

WARNING Cache hit for _get_gsheet_to_df
WARNING unmatched_keys=['email_verification', 'personal_email', 'company_domain', 'company_type', 'company_industry', 'timestamp']
WARNING unmatched_cols=['BoardSeats', 'Roles', 'DealRoles', 'AddressLine1', 'AddressLine2', 'State/Province', 'PostCode', 'Country/Territory/Region', 'Phone', 'Fax', 'origin_timestamp', 'email_timestamp']
WARNING Cache hit for _get_gsheet_to_df
WARNING unmatched_keys=['email_verification', 'personal_email', 'company_type', 'company_industry', 'timestamp']
WARNING unmatched_cols=['Phone', 'PostCode', 'origin_timestamp', 'email_timestamp']

                             origin         full_name first_name last_name                     email                                    linkedin_url                                          job_title                        company_name       city             country                                          biography company_domain
0  Pitchbook.results.200AI.Corp_dev    Oliver Steinig     Oliver   Steinig  oliver.steinig@bosch.com  http://linkedin.com/in/oliver-steinig-68603aa/  Vice President of Business Development and Cor...                  Bosch (Automotive)  Gerlingen  Gerlingen, Germany  Ms. Oliver Steinig serves as Vice President of...            NaN
1  Pitchbook.results.200AI.Corp_dev  Harrick Vin Ph.D    Harrick       Vin       harrick.vin@tcs.com               http://linkedin.com/in/harrickvin                           Chief Technology Officer  Tata Consultancy Services (Mumbai)     Mumbai       Mumbai, India  Dr. Harrick Vin serves as Chief Technology Off...            NaN

In [41]:
# No merge status in this data.
# merge_status_tabs = ["200AI.Corp_dev", "Fort500.Corp_dev"]
# df = ckmktwf.merge_yamm_results_from_gsheet(contact_df, url, merge_status_tabs)

## Acq outreach

In [42]:
url = "https://docs.google.com/spreadsheets/d/1HyglraD02TJwp16wkU_yZZ6jJW51LnBdlaWsVSTNLws"
hgodrapi.print_info_about_google_url(url)

url: 'https://docs.google.com/spreadsheets/d/1HyglraD02TJwp16wkU_yZZ6jJW51LnBdlaWsVSTNLws'
file name: 'Acq outreach'
tab names: '['all', 'Sheet1', 'Sheet14', 'Sheet2', '2025-12-12', '2025-12-16', '2025-12-16-v2', 'Sheet12', 'Sheet13']'
folder path: 'Drive/Outreach pipeline/Campaigns_2025_ToReorg'

In [43]:
tab_name = "_all_"
ckmktwf.analyze_data_type(url, tab_name)

INFO  Reading data:
  url='https://docs.google.com/spreadsheets/d/1HyglraD02TJwp16wkU_yZZ6jJW51LnBdlaWsVSTNLws'
  file_name='Acq outreach'
  tab_name='all'
WARNING Cache hit for _get_gsheet_to_df
INFO  all=(data_from_pitchbook, has_linkedin_profile, has_email)
INFO  Reading data:
  url='https://docs.google.com/spreadsheets/d/1HyglraD02TJwp16wkU_yZZ6jJW51LnBdlaWsVSTNLws'
  file_name='Acq outreach'
  tab_name='Sheet1'
WARNING Cache hit for _get_gsheet_to_df
INFO  Sheet1=(data_from_pitchbook, has_linkedin_profile, has_email, has_email_txt, has_merge_status)
INFO  Reading data:
  url='https://docs.google.com/spreadsheets/d/1HyglraD02TJwp16wkU_yZZ6jJW51LnBdlaWsVSTNLws'
  file_name='Acq outreach'
  tab_name='Sheet14'
WARNING Cache hit for _get_gsheet_to_df
INFO  Sheet14=(data_from_pitchbook, has_linkedin_profile, has_email, has_email_txt, has_merge_status)
INFO  Reading data:
  url='https://docs.google.com/spreadsheets/d/1HyglraD02TJwp16wkU_yZZ6jJW51LnBdlaWsVSTNLws'
  file_name='Acq outreach'
  tab_name='Sheet2'
WARNING Cache hit for _get_gsheet_to_df
INFO  Sheet2=(data_from_pitchbook, has_linkedin_profile, has_email, has_email_txt, has_merge_status)
INFO  Reading data:
  url='https://docs.google.com/spreadsheets/d/1HyglraD02TJwp16wkU_yZZ6jJW51LnBdlaWsVSTNLws'
  file_name='Acq outreach'
  tab_name='2025-12-12'
WARNING Cache hit for _get_gsheet_to_df
INFO  2025-12-12=(data_from_pitchbook, has_linkedin_profile, has_email, has_email_txt, has_merge_status)
INFO  Reading data:
  url='https://docs.google.com/spreadsheets/d/1HyglraD02TJwp16wkU_yZZ6jJW51LnBdlaWsVSTNLws'
  file_name='Acq outreach'
  tab_name='2025-12-16'
WARNING Cache hit for _get_gsheet_to_df
INFO  2025-12-16=(data_from_pitchbook, has_linkedin_profile, has_email, has_email_txt, has_merge_status)
INFO  Reading data:
  url='https://docs.google.com/spreadsheets/d/1HyglraD02TJwp16wkU_yZZ6jJW51LnBdlaWsVSTNLws'
  file_name='Acq outreach'
  tab_name='2025-12-16-v2'
WARNING Cache hit for _get_gsheet_to_df
INFO  2025-12-16-v2=(data_from_pitchbook, has_linkedin_profile, has_email, has_email_txt, has_merge_status)
INFO  Reading data:
  url='https://docs.google.com/spreadsheets/d/1HyglraD02TJwp16wkU_yZZ6jJW51LnBdlaWsVSTNLws'
  file_name='Acq outreach'
  tab_name='Sheet12'
WARNING Cache hit for _get_gsheet_to_df
INFO  Sheet12=(data_from_pitchbook, has_linkedin_profile, has_email, has_email_txt)
INFO  Reading data:
  url='https://docs.google.com/spreadsheets/d/1HyglraD02TJwp16wkU_yZZ6jJW51LnBdlaWsVSTNLws'
  file_name='Acq outreach'
  tab_name='Sheet13'
WARNING Cache hit for _get_gsheet_to_df
INFO  Sheet13=(data_from_pitchbook, has_linkedin_profile, has_email, has_email_txt)

In [ ]:
# tab_names = ['Sheet1', 'Sheet14', 'all', 'Sheet2', '2025-12-12', '2025-12-16', '2025-12-16-v2', 'Sheet12', 'Sheet13']
# tab_name = tab_names[0]
# normalize = True
# contact_df = ckmktwf.get_data_from_fuzzy_column_matching(url, tab_name, normalize)
# contact_df.head(2)

In [ ]:
tab_name = "all"
normalize = True
contact_df = ckmktwf.get_data_from_fuzzy_column_matching(
    url, tab_name, normalize
)
contact_df.head(2)

In [ ]:
merge_status_tabs = [
    "Sheet1",
    "Sheet14",
    "Sheet2",
    "2025-12-12",
    "2025-12-16",
    "2025-12-16-v2",
]

contact_df = ckmktwf.merge_yamm_results_from_gsheet(
    contact_df, url, merge_status_tabs
)

In [ ]:
df.head(2)

In [ ]:
ckmktwf.print_stats(contact_df)

## pitchbook.Outreach_AI_companies

In [ ]:
url = "https://docs.google.com/spreadsheets/d/1GnnmtGTrHDwMP77VylEK0bSF_RLUV5BWf1iGmxuBQpI"
hgodrapi.print_info_about_google_url(url)

In [ ]:
tab_name = "_all_"
ckmktwf.analyze_data_type(url, tab_name)

In [ ]:
tab_name = ["2025-12-03", "2025-12-03-v2"]
normalize = True
contact_df = ckmktwf.get_data_from_fuzzy_column_matching(
    url, tab_name, normalize
)
contact_df.head(2)
print(contact_df.shape)

In [ ]:
merge_status_tabs = ["2025-12-03", "2025-12-03-v2"]
contact_df = ckmktwf.merge_yamm_results_from_gsheet(
    contact_df, url, merge_status_tabs
)

display(contact_df.head(2))

ckmktwf.print_stats(contact_df)

## MA_targets_10k_persons.2025-12-25

In [ ]:
url = "https://docs.google.com/spreadsheets/d/1uSS5h5f3bcWxCFxg90TTB46296JgnFGQeKDaIKtz_84"
hgodrapi.print_info_about_google_url(url)

tab_name = "_all_"
ckmktwf.analyze_data_type(url, tab_name)

## Connect to MA on LinkedIn

In [ ]:
url = "https://docs.google.com/spreadsheets/d/1tXnir8P5VjBxvbQOgJZmArRa7K__J7Fy90rWZtIxXTE"
hgodrapi.print_info_about_google_url(url)

tab_name = "_all_"
ckmktwf.analyze_data_type(url, tab_name)

In [ ]:
url = "https://docs.google.com/spreadsheets/d/1vfWbjN7aYYOdRKwvGs03p-wMQVKgRkpjvVpb-lbhe4A"
hgodrapi.print_info_about_google_url(url)

tab_name = "_all_"
ckmktwf.analyze_data_type(url, tab_name)

In [ ]:
url = "https://docs.google.com/spreadsheets/d/1t4zpgpNMVoBXnjOy1b8e0F15dPHUyxqXAYtp9yFewE4"
hgodrapi.print_info_about_google_url(url)

tab_name = "_all_"
ckmktwf.analyze_data_type(url, tab_name)

In [ ]:
url = "https://docs.google.com/spreadsheets/d/1ehxS764nQYJAtz24YG2oxNPmLYbY04AYWQCU9nDQSko"
hgodrapi.print_info_about_google_url(url)

tab_name = "_all_"
ckmktwf.analyze_data_type(url, tab_name)

In [ ]:
url = "https://docs.google.com/spreadsheets/d/14ekmwAgpIxRzrf8EZeaZB8hudT7-PHGYb0BzK4jpdj8/edit?gid=887396004#gid=887396004"
hgodrapi.print_info_about_google_url(url)

tab_name = "_all_"
ckmktwf.analyze_data_type(url, tab_name, log_level=logging.INFO)

In [ ]:
db_path = "test.db"
id_ = 1
name = "email.partnership.top200ai.cxo"
type_ = "email"
description = ""
message = """
Hi Aaron,

I'm GP Saggese, and I teach machine learning at the University of Maryland, where my team is developing new methods that let LLMs reason explicitly about probability and time.

We're exploring partnerships with product teams who could benefit from advanced AI that understands probability and time. Given Box's focus on collaboration and document management, I see a few areas where these capabilities could be impactful, such as:  
- predicting document utilization trends for better resource allocation  
- forecasting compliance timelines within workflows  
- analyzing user engagement patterns to enhance the Box experience  

We have deployed this to early partners, and we have already $1M ARR in less than 12 months.

Would someone on your team be open to a brief 10-minute conversation to see if any of this aligns with Box's roadmap?
"""
start_date = pd.Timestamp.now()
num_targets = 0

ckmktwf.create_campaign_info_id(
    db_path, id_, name, type_, description, message, start_date, num_targets
)

## Acq12

In [ ]:
url = "https://docs.google.com/spreadsheets/d/1pQ8JCCI9bMQ_woOZJ0P4uRdUZvZP-rPJv9xnycRMw2Y/edit?gid=1923055155#gid=1923055155"

hgodrapi.print_info_about_google_url(url)

tab_name = "All"
ckmktwf.analyze_data_type(url, tab_name)

In [ ]:
email_tab = "All"
merge_status_tabs = (
    "20250210-1 20250211-2 20250212-3 20250212-4 20250213-5 20250213-6".split()
)

df = ckmktwf.load_all_yamm_results(url, email_tab, merge_status_tabs)