# Imports

In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import helpers.hgoogle_drive_api as hgodrapi

hgodrapi.install_needed_modules()

Module 'google' is already installed.
Module 'googleapiclient' is already installed.
Module 'gspread' is already installed.

In [3]:
import logging

import pandas as pd

# /venv/lib/python3.12/site-packages/gspread_pandas/spread.py:401: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)` .replace("", np.nan)
pd.set_option("future.no_silent_downcasting", True)

import helpers.hdbg as hdbg
import helpers.henv as henv
import helpers.hpandas as hpandas
import helpers.hprint as hprint

#
hdbg.init_logger(verbosity=logging.INFO)
_LOG = logging.getLogger(__name__)

#
_LOG.info("%s", henv.get_system_signature()[0])
hnotebook.config_notebook()

WARNING: Running in Jupyter
INFO  > cmd='/venv/lib/python3.12/site-packages/ipykernel_launcher.py -f /home/.local/share/jupyter/runtime/kernel-1285dc1c-9bb3-438f-839a-8dbf7fb05595.json'

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (arm64v8)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

INFO  # System signature
  # Container version
    container_version='2.0.0'
    changelog_version='2.2.0'
  # Git info
    branch_name='CsfyTask7819_Add_blogs'
    hash='2b64a6ee5c'
    # Last commits:
      * 2b64a6ee5c GP Saggese Update                                                            (    2 days ago) Thu Dec 25 01:55:48 2025  (HEAD -> CsfyTask7819_Add_blogs, origin/CsfyTask7819_Add_blogs)
      * 3cfa583380 GP Saggese Update                                                            (    2 days ago) Thu Dec 25 01:47:58 2025
      * 683e50c1fc GP Saggese Update                                                            (    2 days ago) Thu Dec 25 00:45:57 2025
  # Platform info
    system=Linux
    node name=760242bdb197
    release=6.10.14-linuxkit
    version=#1 SMP Tue Apr 15 16:00:54 UTC 2025
    machine=aarch64
    processor=aarch64
  # psutils info
    cpu count=8
    cpu freq=None
    memory=svmem(total=16749285376, available=14102679552, percent=15.8, used=2383720448, free=12108525568, active=3295920128, inactive=883548160, buffers=319672320, cached=1937367040, shared=876544, slab=294907904)
    disk usage=sdiskusage(total=270233210880, used=154695315456, free=101777281024, percent=60.3)
  # Docker info
    has_docker=True
    docker_version='28.1.1'
    docker_needs_sudo=False
    has_privileged_mode=True
    is_inside_docker=True
    has_sibling_containers_support=True
    has_docker_dind_support=True
  # Packages
    python: 3.12.3
    cvxopt: 1.3.2
    cvxpy: 1.5.3
    gluonnlp: ?
    gluonts: ?
    joblib: 1.4.2
    mxnet: ?
    numpy: 2.1.3
    pandas: 2.2.3
    pyarrow: 18.0.0
    scipy: 1.14.1
    seaborn: 0.13.2
    sklearn: 1.5.2
    statsmodels: 0.14.4

In [13]:
import helpers.hgoogle_drive_api as hgodrapi

# Get credentials first.
credentials = hgodrapi.get_credentials(
    service_key_path="/home/.config/gspread_pandas/google_secret.json"
)

import ck_marketing.workflows as ckmktwf
import ck_marketing.plugins as ckmktpi

import importlib

importlib.reload(ckmktwf)
importlib.reload(ckmktpi)

# Load Contact data

In [ ]:
contact_dfs = []

In [16]:
# normalize = True
normalize = False
url = "https://docs.google.com/spreadsheets/d/14ekmwAgpIxRzrf8EZeaZB8hudT7-PHGYb0BzK4jpdj8"
tab_name = "phantombuster-all-leads-12262025.csv"
tag = ""
df_tmp = ckmktwf.get_data_from_PhantomBuster_All_Leads(
    url, tab_name, tag, normalize
)

df_tmp.head(2)

,linkedinProfileUrl,salesNavigatorProfileUrl,fullName,firstName,lastName,companyName,linkedinCompanyUrl,salesNavigatorCompanyUrl,companyWebsite,personalWebsite,linkedinJobTitle,linkedinJobDateRange,linkedinJobLocation,companyIndustry,linkedinHeadline,location,professionalEmail1,professionalEmail2,personalEmail1,phoneNumber1,phoneNumber2,civility,twitterProfileUrl,website1,website2,linkedinFollowersCount,linkedinOpenProfile,linkedinDescription,linkedinSkillsLabel,previousCompanyName,linkedinPreviousCompanyUrl,linkedinPreviousCompanySlug,linkedinPreviousJobTitle,linkedinPreviousJobDateRange,linkedinPreviousJobLocation,linkedinJobDescription,linkedinPreviousJobDescription,linkedinSchoolName,linkedinSchoolCompanyUrl,linkedinSchoolCompanySlug,linkedinSchoolDegree,linkedinSchoolDateRange,linkedinSchoolDescription,linkedinPreviousSchoolName,linkedinPreviousSchoolCompanyUrl,linkedinPreviousSchoolCompanySlug,linkedinPreviousSchoolDegree,linkedinPreviousSchoolDateRange,linkedinPreviousSchoolDescription,linkedinMutualConnectionsUrl,linkedinProfileSlug,salesNavigatorProfileSlug,linkedinCompanySlug,linkedinProfileId,linkedinProfileUrn,linkedinIsHiringBadge,linkedinIsOpenToWorkBadge,id,connectionDegree,createdAt,updatedAt,createdBy,updatedBy,origin,biography
0,https://linkedin.com/in/lin-benjamin,,benjamin lin,benjamin,lin,,,,,,,,,,Semi-retired,"Rockville, MD",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,lin-benjamin,,,,,,,7.681433e+15,,7/6/2023,7/6/2023,Deleted Phantom (2912309769837644),Deleted Phantom (2912309769837644),PB.PhantomBuster_All_Leads.,Semi-retired; ;
1,https://linkedin.com/in/jonathan-goldstine-481...,,Jonathan Goldstine,Jonathan,Goldstine,,,,,,,,,,Retired,Knoxville Metropolitan Area,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,jonathan-goldstine-481b5b8,,,,,,,6.100642e+15,,7/6/2023,7/6/2023,Deleted Phantom (2912309769837644),Deleted Phantom (2912309769837644),PB.PhantomBuster_All_Leads.,Retired; ;

In [17]:
df_tmp.nunique()

linkedinProfileUrl                   13094
salesNavigatorProfileUrl              4874
fullName                             12959
firstName                             5133
lastName                              9226
companyName                           5070
linkedinCompanyUrl                    4605
salesNavigatorCompanyUrl               358
companyWebsite                        2179
personalWebsite                       1523
linkedinJobTitle                      5064
linkedinJobDateRange                   879
linkedinJobLocation                   1659
companyIndustry                        141
linkedinHeadline                     11713
location                              1739
professionalEmail1                    1201
professionalEmail2                      14
personalEmail1                         599
phoneNumber1                           773
phoneNumber2                            22
civility                                 3
twitterProfileUrl                      428
website1                              1523
website2                                43
linkedinFollowersCount                4588
linkedinOpenProfile                      3
linkedinDescription                   6382
linkedinSkillsLabel                   8220
previousCompanyName                   5949
linkedinPreviousCompanyUrl            5227
linkedinPreviousCompanySlug           5227
linkedinPreviousJobTitle              5339
linkedinPreviousJobDateRange          4606
linkedinPreviousJobLocation           1701
linkedinJobDescription                4782
linkedinPreviousJobDescription        5018
linkedinSchoolName                    1794
linkedinSchoolCompanyUrl              2062
linkedinSchoolCompanySlug             2062
linkedinSchoolDegree                  3563
linkedinSchoolDateRange               1286
linkedinSchoolDescription             1835
linkedinPreviousSchoolName            2273
linkedinPreviousSchoolCompanyUrl      2311
linkedinPreviousSchoolCompanySlug     2311
linkedinPreviousSchoolDegree          3021
linkedinPreviousSchoolDateRange       1035
linkedinPreviousSchoolDescription     1342
linkedinMutualConnectionsUrl          9721
linkedinProfileSlug                  13094
salesNavigatorProfileSlug             4874
linkedinCompanySlug                   4605
linkedinProfileId                     9102
linkedinProfileUrn                    9721
linkedinIsHiringBadge                    3
linkedinIsOpenToWorkBadge                3
id                                   13094
connectionDegree                         5
createdAt                              202
updatedAt                              246
createdBy                               57
updatedBy                               62
origin                                   1
biography                            12012
dtype: int64

In [19]:
df_tmp.iloc[-1]

linkedinProfileUrl                               https://linkedin.com/in/austinrmartin
salesNavigatorProfileUrl
fullName                                                                 Austin Martin
firstName                                                                       Austin
lastName                                                                        Martin
companyName                                                                       Snyk
linkedinCompanyUrl
salesNavigatorCompanyUrl
companyWebsite
personalWebsite
linkedinJobTitle                     Executive Vice President, Strategy and Operations
linkedinJobDateRange                                                    2020 - Present
linkedinJobLocation                               Boston, Massachusetts, United States
companyIndustry
linkedinHeadline                                  EVP, Strategy and Operations at Snyk
location                                                                Greater Boston
professionalEmail1
professionalEmail2
personalEmail1
phoneNumber1
phoneNumber2
civility
twitterProfileUrl
website1
website2
linkedinFollowersCount                                                            2394
linkedinOpenProfile                                                                 No
linkedinDescription                  In my career in the tech industry, I have seen...
linkedinSkillsLabel                  Analytics, Strategy, Cloud Computing, Manageme...
previousCompanyName                                                     Veeam Software
linkedinPreviousCompanyUrl
linkedinPreviousCompanySlug
linkedinPreviousJobTitle                Senior Vice President, Strategy and Operations
linkedinPreviousJobDateRange                                               2016 - 2020
linkedinPreviousJobLocation                    Baar, Zug, Switzerland & Greater Boston
linkedinJobDescription
linkedinPreviousJobDescription       Veeam is the leader in backup, recovery and da...
linkedinSchoolName                                      MIT Sloan School of Management
linkedinSchoolCompanyUrl                          https://www.linkedin.com/school/1501
linkedinSchoolCompanySlug                                                         1501
linkedinSchoolDegree                        Master of Business Administration (M.B.A.)
linkedinSchoolDateRange                                                    2005 - 2007
linkedinSchoolDescription
linkedinPreviousSchoolName                                       Georgetown University
linkedinPreviousSchoolCompanyUrl                  https://www.linkedin.com/school/4794
linkedinPreviousSchoolCompanySlug                                                 4794
linkedinPreviousSchoolDegree         Bachelor of Arts (B.A.), Double Major: Governm...
linkedinPreviousSchoolDateRange                                            1995 - 1999
linkedinPreviousSchoolDescription
linkedinMutualConnectionsUrl         https://www.linkedin.com/search/results/people...
linkedinProfileSlug                                                      austinrmartin
salesNavigatorProfileSlug
linkedinCompanySlug
linkedinProfileId                                                              5996515
linkedinProfileUrn                             ACoAAABbf-MB108jntejXhvCxjc7e94w16Vgquo
linkedinIsHiringBadge                                                               No
linkedinIsOpenToWorkBadge                                                           No
id                                                                  2049237077169555.0
connectionDegree                                                                   2nd
createdAt                                                                   12/26/2025
updatedAt                                                                   12/26/2025
createdBy                                                       LinkedIn Outreach - MA
updatedBy                                                       LinkedIn Outreach - MA
origin                                                     PB.PhantomBuster_All_Leads.
biography                            EVP, Strategy and Operations at Snyk; In my ca...
Name: 13093, dtype: object

In [21]:
df_tmp["createdBy"].unique()

array(['Deleted Phantom (2912309769837644)',
       'Deleted Phantom (6613256456765567)',
       'Deleted Phantom (3933308360008191)',
       'Deleted Phantom (4809903115550081)',
       'Deleted Phantom (2854373113210911)',
       'Deleted Phantom (3593602419926765)',
       'Deleted Phantom (4693471271530053)',
       'Deleted Phantom (3630865986526313)',
       'Deleted Phantom (1503192626128729)',
       'Deleted Phantom (5767607159170031)',
       'Deleted Phantom (2130689551487885)',
       'Deleted Phantom (5098450889728814)',
       'Deleted Phantom (8802251460861272)',
       'Deleted Phantom (2101622270246586)',
       'Deleted Phantom (3811239139225485)',
       'Deleted Phantom (3296134215680195)',
       'Deleted Phantom (1285627962371177)',
       'Deleted Phantom (2321810255353154)',
       'Deleted Phantom (2471526793293821)',
       'Deleted Phantom (3665151608761564)',
       'Deleted Phantom (5253838792782259)',
       'Deleted Phantom (8731682607109626)',
       'Deleted Phantom (795029239791557)',
       'Deleted Phantom (1809505480671122)',
       'Deleted Phantom (2162325412186296)',
       'Deleted Phantom (3104516552247198)',
       'Deleted Phantom (3560143695278238)',
       'Deleted Phantom (1798434325584088)',
       'Deleted Phantom (335158633373864)',
       'Deleted Phantom (3357366643371668)',
       'Deleted Phantom (6231215137480761)',
       'Deleted Phantom (6296295146374308)',
       'Deleted Phantom (6254094769946227)',
       'Deleted Phantom (2149414348150491)',
       'Deleted Phantom (2037055648453449)',
       'Deleted Phantom (6042904722317134)',
       'Deleted Phantom (7890616458359264)',
       'Deleted Phantom (5078364483070641)',
       'Deleted Phantom (404146117318769)',
       'Deleted Phantom (2580268935041081)',
       'Deleted Phantom (6442588002346404)',
       'Deleted Phantom (8066384773331976)',
       'Deleted Phantom (6320215207580661)',
       'Deleted Phantom (5276371940921545)',
       'Deleted Phantom (2228606163430093)',
       'Deleted Phantom (842771612674527)',
       'Deleted Phantom (4749658629091174)',
       'Deleted Phantom (3996217881930177)',
       'Deleted Phantom (6291494483500543)',
       'Deleted Phantom (1346439034499902)',
       'Deleted Phantom (8130401104731945)',
       'LinkedIn Auto Invitation Accepter',
       'Deleted Phantom (4763478576385993)',
       'Deleted Phantom (1314085960650129)',
       '[Deleted Phantom] (undefined)', 'LinkedIn Outreach - MA',
       'MA_targets_10k_persons'], dtype=object)

In [26]:
# tag = "Deleted Phantom (1314085960650129)"
# tag = "[Deleted Phantom] (undefined)', 'LinkedIn Outreach - MA"
# tag = 'LinkedIn Auto Invitation Accepter'
tag = "MA_targets_10k_persons"
mask = df_tmp["createdBy"] == tag
mask.sum()

np.int64(982)

In [38]:
url = "https://docs.google.com/spreadsheets/d/1uSS5h5f3bcWxCFxg90TTB46296JgnFGQeKDaIKtz_84/edit"
df1 = ckmktwf.get_gsheet_to_df(url, None)
# print(hpandas.head(df1))
print(df1.shape)
display(df1.head(2))

url = "https://docs.google.com/spreadsheets/d/1PZkWY8TYuEx7_WapG74AiwLLoLrDeGuHrQT8y3N4GXg/edit"
df2 = ckmktwf.get_gsheet_to_df(url, None)
# display(df2.head(2))
print(df2.shape)

(1000, 34)

                                          profileUrl        fullName firstName  lastName companyName                                 title companyId                                   companyUrl                      regularCompanyUrl                                            summary                                   titleDescription               industry                      companyLocation                                 location            durationInRole            durationInCompany pastExperienceCompanyName pastExperienceCompanyUrl pastExperienceCompanyTitle pastExperienceDate pastExperienceDuration connectionDegree                                    profileImageUrl  sharedConnectionsCount            name                                     vmid                                 linkedInProfileUrl isPremium isOpenLink                                              query                 timestamp                   defaultProfileUrl  searchAccountProfileId searchAccountProfileName
0  https://www.linkedin.com/sales/lead/ACwAACIIGw...     Fawaz Ahmar     Fawaz     Ahmar         PwC   Senior Director - FS / M&A Advisory      1044  https://www.linkedin.com/sales/company/1044  https://www.linkedin.com/company/1044  Fawaz is an experienced Senior Director within...                                                     Professional Services      London, England, United Kingdom        New York, New York, United States           8 years in role           8 years in company                                                                                                                                      2nd  https://media.licdn.com/dms/image/v2/C4D03AQFe...                       2     Fawaz Ahmar  ACwAACIIGwQBarOTcv9cBkPkS4qb143voXG2rdA  https://www.linkedin.com/in/ACwAACIIGwQBarOTcv...      TRUE      FALSE  https://www.linkedin.com/sales/search/people?q...  2025-12-23T22:22:40.983Z  https://linkedin.com/in/fawazahmar                 8207060   Giacinto Paolo Saggese
1  https://www.linkedin.com/sales/lead/ACwAAAALVr...  David Popowitz     David  Popowitz       Adobe  Vice President Corporate Development      1480  https://www.linkedin.com/sales/company/1480  https://www.linkedin.com/company/1480  Father of 3 boys -  mostly loud.\nTennis playe...  Lead the corporate development and integration...   Software Development  San Jose, California, United States  Redwood City, California, United States  1 year 10 months in role  1 year 10 months in company                                                                                                                                      2nd  https://media.licdn.com/dms/image/v2/C4E03AQHr...                      16  David Popowitz  ACwAAAALVrgBfGyT-Je-n-Rqw0znHen6jAfI01U  https://www.linkedin.com/in/ACwAAAALVrgBfGyT-J...     FALSE      FALSE  https://www.linkedin.com/sales/search/people?q...  2025-12-23T22:22:40.983Z    https://linkedin.com/in/popowitz                 8207060   Giacinto Paolo Saggese

(1000, 34)

In [40]:
df1.equals(df2)

True

In [ ]:
contact_dfs.append(df_tmp)

In [ ]:
ckmktwf.print_contact_df_stats(df_tmp)

## Clean up names

In [ ]:
contact_df = ckmktpi.clean_and_track_name_changes(contact_df)

debug_df = ckmktpi.get_debug_clean_name_df(contact_df)
ckmktpi.get_clean_name_stats(contact_df)

In [ ]:
hpandas.filter_df(debug_df, "is_modified", True).head(2)

In [ ]:
contact_df = ckmktpi.merge_clean_names_df(contact_df)

contact_df.head(1)

In [ ]:
# hgodrapi.to_gsheet(
#     hgodrapi.get_credentials(),
#     contact_df,
#     url: str,
#     freeze_rows=True,
# ) -> None:

In [ ]:
# ckmktwf.save_to_gsheet(contact_df)

# Load into DB

In [ ]:
db_path = "test.sql"

In [ ]:
ckmktwf.get_table_count(db_path, "Contact")

In [ ]:
crm_df = ckmktwf.get_as_df(db_path, "Contact")

print(hpandas.head(crm_df))

In [ ]:
crm_df.origin.unique()

In [ ]:
# mode = "assume_no_overlap"
mode = "keep_existing"
_ = ckmktwf.insert_contact_df(db_path, contact_df, mode)

In [ ]:
crm_df = ckmktwf.get_as_df(db_path, "Contact")

print(hpandas.head(crm_df))
print(crm_df.origin.unique())

ckmktwf.get_table_count(db_path, "Contact")